(cl:in-package morai_msgs-msg)
(cl:export '(POSITION_X-VAL
          POSITION_X
          POSITION_Y-VAL
          POSITION_Y
          POSITION_Z-VAL
          POSITION_Z
          VELOCITY_X-VAL
          VELOCITY_X
          VELOCITY_Y-VAL
          VELOCITY_Y
          VELOCITY_Z-VAL
          VELOCITY_Z
          ACCELERATION_X-VAL
          ACCELERATION_X
          ACCELERATION_Y-VAL
          ACCELERATION_Y
          ACCELERATION_Z-VAL
          ACCELERATION_Z
          MAX_LATERAL_ACCELERATION-VAL
          MAX_LATERAL_ACCELERATION
          YAW_ANGLE-VAL
          YAW_ANGLE
          FRONT_WHEEL_ANGLE-VAL
          FRONT_WHEEL_ANGLE
          THROTTLE-VAL
          THROTTLE
          BRAKE-VAL
          BRAKE
          TTC-VAL
          TTC
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          FALLBACK_TRIGGER-VAL
          FALLBACK_TRIGGER
          MRM_SELECT_INFO-VAL
          MRM_SELECT_INFO
          IS_COLLISION-VAL
          IS_COLLISION
          WAY_OFF_DISTANCE-VAL
          WAY_OFF_DISTANCE
          SUR_WAY_OFF_DISTANCE-VAL
          SUR_WAY_OFF_DISTANCE
))