// Generated by gencpp from file morai_msgs/Competition.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_COMPETITION_H
#define MORAI_MSGS_MESSAGE_COMPETITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct Competition_
{
  typedef Competition_<ContainerAllocator> Type;

  Competition_()
    : header()
    , start_signal(0)
    , team_name()
    , mission_success(false)  {
    }
  Competition_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , start_signal(0)
    , team_name(_alloc)
    , mission_success(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _start_signal_type;
  _start_signal_type start_signal;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _team_name_type;
  _team_name_type team_name;

   typedef uint8_t _mission_success_type;
  _mission_success_type mission_success;





  typedef boost::shared_ptr< ::morai_msgs::Competition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::Competition_<ContainerAllocator> const> ConstPtr;

}; // struct Competition_

typedef ::morai_msgs::Competition_<std::allocator<void> > Competition;

typedef boost::shared_ptr< ::morai_msgs::Competition > CompetitionPtr;
typedef boost::shared_ptr< ::morai_msgs::Competition const> CompetitionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::Competition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::Competition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::Competition_<ContainerAllocator1> & lhs, const ::morai_msgs::Competition_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.start_signal == rhs.start_signal &&
    lhs.team_name == rhs.team_name &&
    lhs.mission_success == rhs.mission_success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::Competition_<ContainerAllocator1> & lhs, const ::morai_msgs::Competition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::Competition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::Competition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::Competition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::Competition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::Competition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::Competition_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::Competition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bcb03cff40c27e30f70555863407010b";
  }

  static const char* value(const ::morai_msgs::Competition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbcb03cff40c27e30ULL;
  static const uint64_t static_value2 = 0xf70555863407010bULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::Competition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/Competition";
  }

  static const char* value(const ::morai_msgs::Competition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::Competition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 start_signal\n"
"string team_name \n"
"bool mission_success\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::morai_msgs::Competition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::Competition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.start_signal);
      stream.next(m.team_name);
      stream.next(m.mission_success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Competition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::Competition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::Competition_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "start_signal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start_signal);
    s << indent << "team_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.team_name);
    s << indent << "mission_success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mission_success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_COMPETITION_H
