// Generated by gencpp from file morai_msgs/EgoDetailStatus.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_EGODETAILSTATUS_H
#define MORAI_MSGS_MESSAGE_EGODETAILSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace morai_msgs
{
template <class ContainerAllocator>
struct EgoDetailStatus_
{
  typedef EgoDetailStatus_<ContainerAllocator> Type;

  EgoDetailStatus_()
    : header()
    , unique_id(0)
    , front_left_location()
    , front_right_location()
    , rear_left_location()
    , rear_right_location()
    , turn_signal_lamp(0)  {
    }
  EgoDetailStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , unique_id(0)
    , front_left_location(_alloc)
    , front_right_location(_alloc)
    , rear_left_location(_alloc)
    , rear_right_location(_alloc)
    , turn_signal_lamp(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _unique_id_type;
  _unique_id_type unique_id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _front_left_location_type;
  _front_left_location_type front_left_location;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _front_right_location_type;
  _front_right_location_type front_right_location;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _rear_left_location_type;
  _rear_left_location_type rear_left_location;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _rear_right_location_type;
  _rear_right_location_type rear_right_location;

   typedef uint8_t _turn_signal_lamp_type;
  _turn_signal_lamp_type turn_signal_lamp;





  typedef boost::shared_ptr< ::morai_msgs::EgoDetailStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::EgoDetailStatus_<ContainerAllocator> const> ConstPtr;

}; // struct EgoDetailStatus_

typedef ::morai_msgs::EgoDetailStatus_<std::allocator<void> > EgoDetailStatus;

typedef boost::shared_ptr< ::morai_msgs::EgoDetailStatus > EgoDetailStatusPtr;
typedef boost::shared_ptr< ::morai_msgs::EgoDetailStatus const> EgoDetailStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::EgoDetailStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::EgoDetailStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::EgoDetailStatus_<ContainerAllocator1> & lhs, const ::morai_msgs::EgoDetailStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.unique_id == rhs.unique_id &&
    lhs.front_left_location == rhs.front_left_location &&
    lhs.front_right_location == rhs.front_right_location &&
    lhs.rear_left_location == rhs.rear_left_location &&
    lhs.rear_right_location == rhs.rear_right_location &&
    lhs.turn_signal_lamp == rhs.turn_signal_lamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::EgoDetailStatus_<ContainerAllocator1> & lhs, const ::morai_msgs::EgoDetailStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::EgoDetailStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::EgoDetailStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::EgoDetailStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::EgoDetailStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::EgoDetailStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::EgoDetailStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::EgoDetailStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d27a205035704912eadcd8056b5dd496";
  }

  static const char* value(const ::morai_msgs::EgoDetailStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd27a205035704912ULL;
  static const uint64_t static_value2 = 0xeadcd8056b5dd496ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::EgoDetailStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/EgoDetailStatus";
  }

  static const char* value(const ::morai_msgs::EgoDetailStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::EgoDetailStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 unique_id\n"
"geometry_msgs/Point front_left_location\n"
"geometry_msgs/Point front_right_location\n"
"geometry_msgs/Point rear_left_location\n"
"geometry_msgs/Point rear_right_location\n"
"uint8 turn_signal_lamp\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::morai_msgs::EgoDetailStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::EgoDetailStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.unique_id);
      stream.next(m.front_left_location);
      stream.next(m.front_right_location);
      stream.next(m.rear_left_location);
      stream.next(m.rear_right_location);
      stream.next(m.turn_signal_lamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EgoDetailStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::EgoDetailStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::EgoDetailStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "unique_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.unique_id);
    s << indent << "front_left_location: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.front_left_location);
    s << indent << "front_right_location: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.front_right_location);
    s << indent << "rear_left_location: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.rear_left_location);
    s << indent << "rear_right_location: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.rear_right_location);
    s << indent << "turn_signal_lamp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.turn_signal_lamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_EGODETAILSTATUS_H
