// Generated by gencpp from file morai_msgs/GripperState.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_GRIPPERSTATE_H
#define MORAI_MSGS_MESSAGE_GRIPPERSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace morai_msgs
{
template <class ContainerAllocator>
struct GripperState_
{
  typedef GripperState_<ContainerAllocator> Type;

  GripperState_()
    : release_limit(false)
    , grip_limit(false)  {
    }
  GripperState_(const ContainerAllocator& _alloc)
    : release_limit(false)
    , grip_limit(false)  {
  (void)_alloc;
    }



   typedef uint8_t _release_limit_type;
  _release_limit_type release_limit;

   typedef uint8_t _grip_limit_type;
  _grip_limit_type grip_limit;





  typedef boost::shared_ptr< ::morai_msgs::GripperState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::GripperState_<ContainerAllocator> const> ConstPtr;

}; // struct GripperState_

typedef ::morai_msgs::GripperState_<std::allocator<void> > GripperState;

typedef boost::shared_ptr< ::morai_msgs::GripperState > GripperStatePtr;
typedef boost::shared_ptr< ::morai_msgs::GripperState const> GripperStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::GripperState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::GripperState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::GripperState_<ContainerAllocator1> & lhs, const ::morai_msgs::GripperState_<ContainerAllocator2> & rhs)
{
  return lhs.release_limit == rhs.release_limit &&
    lhs.grip_limit == rhs.grip_limit;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::GripperState_<ContainerAllocator1> & lhs, const ::morai_msgs::GripperState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::GripperState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::GripperState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::GripperState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::GripperState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::GripperState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::GripperState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::GripperState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc4558688d7d357989e10d3f6df1fa69";
  }

  static const char* value(const ::morai_msgs::GripperState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc4558688d7d3579ULL;
  static const uint64_t static_value2 = 0x89e10d3f6df1fa69ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::GripperState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/GripperState";
  }

  static const char* value(const ::morai_msgs::GripperState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::GripperState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool release_limit\n"
"bool grip_limit\n"
;
  }

  static const char* value(const ::morai_msgs::GripperState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::GripperState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.release_limit);
      stream.next(m.grip_limit);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::GripperState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::GripperState_<ContainerAllocator>& v)
  {
    s << indent << "release_limit: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.release_limit);
    s << indent << "grip_limit: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.grip_limit);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_GRIPPERSTATE_H
