// Generated by gencpp from file morai_msgs/RobotPose.msg
// DO NOT EDIT!


#ifndef MORAI_MSGS_MESSAGE_ROBOTPOSE_H
#define MORAI_MSGS_MESSAGE_ROBOTPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace morai_msgs
{
template <class ContainerAllocator>
struct RobotPose_
{
  typedef RobotPose_<ContainerAllocator> Type;

  RobotPose_()
    : position_x(0.0)
    , position_y(0.0)
    , position_z(0.0)
    , orientation_x(0.0)
    , orientation_y(0.0)
    , orientation_z(0.0)  {
    }
  RobotPose_(const ContainerAllocator& _alloc)
    : position_x(0.0)
    , position_y(0.0)
    , position_z(0.0)
    , orientation_x(0.0)
    , orientation_y(0.0)
    , orientation_z(0.0)  {
  (void)_alloc;
    }



   typedef float _position_x_type;
  _position_x_type position_x;

   typedef float _position_y_type;
  _position_y_type position_y;

   typedef float _position_z_type;
  _position_z_type position_z;

   typedef float _orientation_x_type;
  _orientation_x_type orientation_x;

   typedef float _orientation_y_type;
  _orientation_y_type orientation_y;

   typedef float _orientation_z_type;
  _orientation_z_type orientation_z;





  typedef boost::shared_ptr< ::morai_msgs::RobotPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morai_msgs::RobotPose_<ContainerAllocator> const> ConstPtr;

}; // struct RobotPose_

typedef ::morai_msgs::RobotPose_<std::allocator<void> > RobotPose;

typedef boost::shared_ptr< ::morai_msgs::RobotPose > RobotPosePtr;
typedef boost::shared_ptr< ::morai_msgs::RobotPose const> RobotPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::morai_msgs::RobotPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::morai_msgs::RobotPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::morai_msgs::RobotPose_<ContainerAllocator1> & lhs, const ::morai_msgs::RobotPose_<ContainerAllocator2> & rhs)
{
  return lhs.position_x == rhs.position_x &&
    lhs.position_y == rhs.position_y &&
    lhs.position_z == rhs.position_z &&
    lhs.orientation_x == rhs.orientation_x &&
    lhs.orientation_y == rhs.orientation_y &&
    lhs.orientation_z == rhs.orientation_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::morai_msgs::RobotPose_<ContainerAllocator1> & lhs, const ::morai_msgs::RobotPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace morai_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::RobotPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::morai_msgs::RobotPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::RobotPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::morai_msgs::RobotPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::RobotPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::morai_msgs::RobotPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::morai_msgs::RobotPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "957c08c29c2c14d2b47dfb19794a6b00";
  }

  static const char* value(const ::morai_msgs::RobotPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x957c08c29c2c14d2ULL;
  static const uint64_t static_value2 = 0xb47dfb19794a6b00ULL;
};

template<class ContainerAllocator>
struct DataType< ::morai_msgs::RobotPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "morai_msgs/RobotPose";
  }

  static const char* value(const ::morai_msgs::RobotPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::morai_msgs::RobotPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 position_x\n"
"float32 position_y\n"
"float32 position_z\n"
"\n"
"float32 orientation_x\n"
"float32 orientation_y\n"
"float32 orientation_z\n"
;
  }

  static const char* value(const ::morai_msgs::RobotPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::morai_msgs::RobotPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position_x);
      stream.next(m.position_y);
      stream.next(m.position_z);
      stream.next(m.orientation_x);
      stream.next(m.orientation_y);
      stream.next(m.orientation_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morai_msgs::RobotPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::morai_msgs::RobotPose_<ContainerAllocator>& v)
  {
    s << indent << "position_x: ";
    Printer<float>::stream(s, indent + "  ", v.position_x);
    s << indent << "position_y: ";
    Printer<float>::stream(s, indent + "  ", v.position_y);
    s << indent << "position_z: ";
    Printer<float>::stream(s, indent + "  ", v.position_z);
    s << indent << "orientation_x: ";
    Printer<float>::stream(s, indent + "  ", v.orientation_x);
    s << indent << "orientation_y: ";
    Printer<float>::stream(s, indent + "  ", v.orientation_y);
    s << indent << "orientation_z: ";
    Printer<float>::stream(s, indent + "  ", v.orientation_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MORAI_MSGS_MESSAGE_ROBOTPOSE_H
